apiVersion: v1
kind: Service
metadata:
  labels:
    app: faults-api
  name: faults-api
spec:
  ports:
  - name: 4203-4203
    port: 4203
    protocol: TCP
    targetPort: 4203
  selector:
    app: faults-api
  type: LoadBalancer
status:
  loadBalancer: {}
